"""Auditable vocabulary used by protected-class marketing safety checks."""

from __future__ import annotations

import re

_PROTECTED_NATIONAL_ORIGIN_TERMS = frozenset(
    {
        "afghan",
        "albanian",
        "algerian",
        "american",
        "argentine",
        "argentinian",
        "armenian",
        "australian",
        "austrian",
        "bahamian",
        "bangladeshi",
        "barbadian",
        "belgian",
        "belizean",
        "bhutanese",
        "bolivian",
        "bosnian",
        "brazilian",
        "british",
        "bulgarian",
        "burmese",
        "cambodian",
        "cameroonian",
        "canadian",
        "chilean",
        "chinese",
        "colombian",
        "congolese",
        "costa rican",
        "croatian",
        "cuban",
        "czech",
        "danish",
        "dominican",
        "dutch",
        "ecuadorian",
        "egyptian",
        "english",
        "eritrean",
        "ethiopian",
        "filipino",
        "finnish",
        "french",
        "german",
        "ghanaian",
        "greek",
        "guatemalan",
        "guyanese",
        "haitian",
        "hmong",
        "honduran",
        "hungarian",
        "icelandic",
        "indian",
        "indonesian",
        "iranian",
        "iraqi",
        "irish",
        "italian",
        "jamaican",
        "japanese",
        "jordanian",
        "kazakh",
        "kenyan",
        "korean",
        "kyrgyz",
        "lao",
        "laotian",
        "latvian",
        "lebanese",
        "liberian",
        "lithuanian",
        "macedonian",
        "malaysian",
        "mexican",
        "mongolian",
        "moroccan",
        "nepalese",
        "nepali",
        "new zealander",
        "nicaraguan",
        "nigerian",
        "norwegian",
        "pakistani",
        "palestinian",
        "panamanian",
        "paraguayan",
        "peruvian",
        "polish",
        "portuguese",
        "puerto rican",
        "romanian",
        "russian",
        "salvadoran",
        "samoan",
        "saudi",
        "senegalese",
        "serbian",
        "singaporean",
        "slovak",
        "slovenian",
        "somali",
        "south african",
        "spanish",
        "sri lankan",
        "sudanese",
        "swedish",
        "swiss",
        "syrian",
        "taiwanese",
        "thai",
        "tongan",
        "trinidadian",
        "turkish",
        "ugandan",
        "ukrainian",
        "uruguayan",
        "uzbek",
        "venezuelan",
        "vietnamese",
        "yemeni",
        "zimbabwean",
    }
)

PROTECTED_NATIONAL_ORIGIN_RE = re.compile(
    r"\b(?:"
    + "|".join(
        re.escape(term).replace(r"\ ", r"[ -]")
        for term in sorted(_PROTECTED_NATIONAL_ORIGIN_TERMS, key=len, reverse=True)
    )
    + r")s?\b",
    re.IGNORECASE,
)
