/**
 * Score anatomy fixtures (wave 3, lane w3-score-anatomy: wow-stage-2,
 * wow-ai-1, wow-stage-3).
 *
 * Nothing here registers by default and there is no registry line: the
 * default GET /api/borrowers/:id/proof (data/leads.ts) is trusted WITH a gap
 * and uses older weights, so score-anatomy.fixture.spec.ts registers these
 * overrides per test with `mockApi.register()`:
 *
 *   - `registerAnatomyProof(mockApi, 'trusted' | 'untrusted')`: the proof
 *     with the live weights (0.35 / 0.30 / 0.15 / 0.10 / 0.10) and the five
 *     deterministic margins; trusted has no gap (the seal renders),
 *     untrusted lists two gaps (it does not);
 *   - `registerRoutedApprove(mockApi, gate?)`: the approve POST answering
 *     with an assignee and a follow-up (the routing line), optionally held
 *     on a RequestGate, plus the ledger read-back;
 *   - `registerExplorerDecisionRows(mockApi)`: an audit explorer page with
 *     one APPROVE row and one VIEW_LEADS row, and the receipt read-back.
 *
 * Every payload is typed against the frontend's own response types and
 * `contractSamples()` exports them for the fixture contract (api-contract
 * lane). Synthetic only: masked ids, `.example` staff, no contact fields.
 */
import type { Borrower360, BorrowerProof, ProofMargin, ProofScoreComponent } from '../../../../src/types';
import type { AuditEventPage, AuditEventRow, DecisionReceipt } from '../../../../src/lib/apiTypes';
import { json, type MockApi } from '../mockApi';
import { PRIMARY_BORROWER, borrowerById } from './borrowers';
import { type RequestGate, ledgerReceipt } from './decisionReceipt';
import { ROUTED_APPROVE_AUDIT_ID, routedApproveResult } from './feedbackGuard';
import { SNAPSHOT_AT } from './reference';

export type AnatomyProofKind = 'trusted' | 'untrusted';

/** The recompute seal's text (scoreAnatomy.copy.ts). */
export const ANATOMY_SEAL = 'Recomputed from lead_scores components: matches';

export const UNTRUSTED_GAPS: readonly string[] = [
  'Borrower dossier and lead_scores were refreshed at different times; dossier 2026-07-14T12:00:00Z, lead_scores 2026-07-13T12:00:00Z.',
  'Recomputed signal strength does not match the borrower dossier displayed value; recomputed 86, dossier 87.',
];

/** The par every margin quotes: the fixture dossier's market_rate 0.04875 ("vs. par 4.88%"). */
export const ANATOMY_PAR = 'par 4.88%';

const PARTS: ReadonlyArray<readonly [ProofScoreComponent['key'], string, number, number]> = [
  ['economic_incentive', 'Economic incentive', 0.35, 98],
  ['intent_trigger', 'Intent trigger', 0.3, 95],
  ['fit', 'Product fit', 0.15, 70],
  ['relationship', 'Relationship', 0.1, 80],
  ['evidence', 'Evidence coverage', 0.1, 90],
];

function components(): ProofScoreComponent[] {
  return PARTS.map(([key, label, weight, value]) => ({
    key,
    label,
    value,
    weight,
    weighted_points: Math.round(value * weight * 100) / 100,
    explanation: `${label} sub-score from mip.gold.lead_scores.`,
    source_fields: [key === 'economic_incentive' ? 'rate_spread_bps' : 'evidence_ids'],
    fair_lending_note: key === 'fit' ? 'Audit note: this signal supports marketing prioritization, not credit eligibility.' : null,
  }));
}

export const ANATOMY_MARGINS: readonly ProofMargin[] = [
  // Generated by backend build_proof_margins for the primary fixture borrower's
  // economics (current_rate 5.715, par 0.04875, spread 84 bps, equity 46%,
  // refi_plus_heloc), so the copy is the builder's own.
  { key: 'spread_screen', label: 'Refi screen', value_text: 'Clears the refi screen by 9 bps', threshold: 'spread 84 bps · screen 75 bps', direction: 'clears', source: 'mip.gold.fn_in_the_money' },
  { key: 'par_break_even', label: 'Par break-even', value_text: 'Drops below the refi screen if 30-year par rises 10 bps to 4.98%', threshold: ANATOMY_PAR, direction: 'flips', source: 'mip.gold.fn_rate_spread' },
  { key: 'equity_floor', label: 'Equity threshold', value_text: 'Clears the home-equity threshold by 11 pts', threshold: 'equity 46% · threshold 35%', direction: 'clears', source: 'mip.gold.fn_next_best_offer' },
  { key: 'offer_flip_equity', label: 'Offer change by equity', value_text: 'Becomes Refinance review at 34% equity', threshold: 'equity 46%', direction: 'flips', source: 'mip.gold.fn_next_best_offer' },
  { key: 'offer_flip_par', label: 'Offer change by par', value_text: 'Becomes Cash-out refinance review if par rises 10 bps to 4.98%', threshold: ANATOMY_PAR, direction: 'flips', source: 'mip.gold.fn_next_best_offer' },
];

export function anatomyProof(borrower: Borrower360, kind: AnatomyProofKind): BorrowerProof {
  const trusted = kind === 'trusted';
  const formula = (label: string, source: string) => ({ label, expression: `${label} inputs`, result: label, source });
  return {
    borrower_id: borrower.borrower_id,
    trusted,
    known_data_gaps: trusted ? [] : [...UNTRUSTED_GAPS],
    generated_from: 'mip.gold.borrower_dossier + mip.gold.lead_scores',
    source_refresh_at: `dossier ${SNAPSHOT_AT} / lead_scores ${SNAPSHOT_AT}`,
    opportunity_score: borrower.opportunity_score,
    signal_strength: borrower.confidence,
    signal_strength_note: 'Signal strength is a deterministic average of the five scoring sub-scores.',
    evidence_confidence_note: 'Evidence confidence is row-level source confidence from gold.evidence_events.',
    score_components: components(),
    score_formula: formula('Opportunity score', 'mip.gold.fn_lead_score'),
    signal_strength_formula: formula('Signal strength', 'mip.gold.lead_scores'),
    rate_spread_formula: formula('Rate spread', 'mip.gold.fn_rate_spread'),
    equity_formula: formula('Equity', 'mip.gold.borrower_dossier'),
    ltv_formula: formula('LTV', 'mip.gold.borrower_dossier'),
    offer_code: borrower.recommended_offer_code ?? 'refi',
    offer_label: borrower.recommended_offer,
    offer_branches: [],
    evidence_rows: borrower.evidence_events.map(({ source_table: _table, ...row }) => row),
    source_assets: ['mip.gold.borrower_dossier', 'mip.gold.lead_scores', 'mip.gold.evidence_events'],
    reproduce: [],
    margins: [...ANATOMY_MARGINS],
  };
}

export function registerAnatomyProof(mockApi: MockApi, kind: AnatomyProofKind): void {
  mockApi.register<BorrowerProof | { detail: string }>('GET', '/api/borrowers/:id/proof', ({ params }) => {
    const borrower = borrowerById(params.id);
    if (!borrower) return json({ detail: `Borrower ${params.id} is not in the fixture population.` }, { status: 404 });
    return json<BorrowerProof>(anatomyProof(borrower, kind));
  });
}

/** The routed approve (assignee + follow-up) and its ledger read-back; the POST may be held. */
export function registerRoutedApprove(mockApi: MockApi, gate: RequestGate | null = null): void {
  mockApi.register('POST', '/api/outreach/approve', async () => {
    if (gate) await gate.hold();
    return routedApproveResult();
  });
  mockApi.register('GET', '/api/audit/receipt/:id', ({ params }) =>
    json<DecisionReceipt>(ledgerReceipt(params.id, PRIMARY_BORROWER, 'approved')),
  );
}

export const EXPLORER_DECISION_ROW: AuditEventRow = {
  event_id: ROUTED_APPROVE_AUDIT_ID,
  actor: 'ledger.approver@summit-mortgage.example',
  action: 'outreach.approve',
  entity_type: 'borrower',
  entity_id: PRIMARY_BORROWER.borrower_id,
  payload_json: { offer_code: PRIMARY_BORROWER.recommended_offer_code ?? null },
  evidence_ids: PRIMARY_BORROWER.evidence_ids.slice(0, 1),
  created_at: '2026-07-14T15:00:04Z',
  event_type: 'APPROVE',
  subject_clip: PRIMARY_BORROWER.clip,
  subject_segment: PRIMARY_BORROWER.segment_codes[0],
  request_id: 'req-anatomy-0001',
  correlation_id: 'corr-anatomy-0001',
};

export const EXPLORER_VIEW_ROW: AuditEventRow = {
  ...EXPLORER_DECISION_ROW,
  event_id: 'evt-anatomy-view-0001',
  actor: 'analyst@summit-mortgage.example',
  action: 'VIEW_LEADS',
  event_type: 'VIEW_LEADS',
  entity_type: 'lead_queue',
  entity_id: 'lead-queue',
  payload_json: {},
  request_id: 'req-anatomy-0002',
  correlation_id: 'corr-anatomy-0002',
};

export function registerExplorerDecisionRows(mockApi: MockApi): void {
  mockApi.register('GET', '/api/audit/events/page', () =>
    json<AuditEventPage>({ items: [EXPLORER_DECISION_ROW, EXPLORER_VIEW_ROW], next_cursor: null }),
  );
  mockApi.register('GET', '/api/audit/receipt/:id', ({ params }) =>
    json<DecisionReceipt>(ledgerReceipt(params.id, PRIMARY_BORROWER, 'approved')),
  );
}

export interface ContractSample {
  method: 'GET' | 'POST';
  pattern: string;
  path: string;
  query: Record<string, string>;
  status: number;
  body: unknown;
}

/** Every payload this module can register, for the fixture contract exporter. */
export function contractSamples(): ContractSample[] {
  const id = PRIMARY_BORROWER.borrower_id;
  return [
    ...(['trusted', 'untrusted'] as const).map((kind) => ({
      method: 'GET' as const,
      pattern: '/api/borrowers/:id/proof',
      path: `/api/borrowers/${id}/proof`,
      query: {},
      status: 200,
      body: anatomyProof(PRIMARY_BORROWER, kind),
    })),
    {
      method: 'POST',
      pattern: '/api/outreach/approve',
      path: '/api/outreach/approve',
      query: {},
      status: 200,
      body: routedApproveResult().body,
    },
    {
      method: 'GET',
      pattern: '/api/audit/events/page',
      path: '/api/audit/events/page',
      query: {},
      status: 200,
      body: { items: [EXPLORER_DECISION_ROW, EXPLORER_VIEW_ROW], next_cursor: null } satisfies AuditEventPage,
    },
    {
      method: 'GET',
      pattern: '/api/audit/receipt/:id',
      path: `/api/audit/receipt/${ROUTED_APPROVE_AUDIT_ID}`,
      query: {},
      status: 200,
      body: ledgerReceipt(ROUTED_APPROVE_AUDIT_ID, PRIMARY_BORROWER, 'approved'),
    },
  ];
}
