#!/usr/bin/env python3
"""Emit frontend/src/types/api.gen.ts from the committed OpenAPI baseline.

Usage:
    python tools/gen_api_types.py --write    # rewrite the TS module
    python tools/gen_api_types.py --check    # exit 1 when the TS module is stale

The input is ``tests/fixtures/openapi_baseline.json``, which
test_openapi_baseline_captures_current_api_surface already pins to the live
app; this tool never imports the backend. ``python
tools/regen_openapi_baseline.py`` rewrites both files in one run.

The output is one type-only module with three parts:

1. ``ResponseSchemas``: the 2xx closure in the PRESENCE view. FastAPI
   serializes every declared field, so every declared property is present
   (``name: T``); nullability comes only from an ``anyOf`` with ``null``. The
   $ref closure of ABSENT_KEY_ROOTS (routes serialized with
   ``response_model_exclude_unset``) keeps its declared ``required`` list.
2. ``RequestSchemas``: the request-body and parameter closure in the DECLARED
   view (``required`` as declared, ``?:`` otherwise).
3. ``ApiOperations``: the canonical ``/api/v1`` operations with their path,
   query and header parameters, body and 2xx ``ok`` union.

Everything is closed and fails closed: exactly the 22 JSON Schema keywords the
baseline uses, three formats, five parameter-object keys, a reviewed header
allowlist (cookies refused), and a content screen over every emitted
description and string literal. A construct outside those sets raises
UnsupportedSchema with its JSON pointer; extend the sets only with a reviewed
golden case in tests/unit/test_api_types_generator.py.

Python 3.11 standard library only: this module imports neither ``backend``
nor any other ``tools`` module.
"""

from __future__ import annotations

import argparse
import difflib
import json
import re
import sys
from collections.abc import Iterable, Iterator
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
BASELINE = ROOT / "tests" / "fixtures" / "openapi_baseline.json"
OUTPUT = ROOT / "frontend" / "src" / "types" / "api.gen.ts"
OUTPUT_REL = "frontend/src/types/api.gen.ts"

BANNER = (
    "// GENERATED by tools/gen_api_types.py from tests/fixtures/openapi_baseline.json. "
    "Do not edit: run `python tools/regen_openapi_baseline.py`."
)

ABSENT_KEY_ROOTS: frozenset[str] = frozenset({"HealthResponse"})
ALLOWED_KEYWORDS: frozenset[str] = frozenset(
    {
        "$ref",
        "additionalProperties",
        "anyOf",
        "const",
        "default",
        "description",
        "enum",
        "exclusiveMinimum",
        "format",
        "items",
        "maxItems",
        "maxLength",
        "maximum",
        "minItems",
        "minLength",
        "minimum",
        "pattern",
        "properties",
        "propertyNames",
        "required",
        "title",
        "type",
    }
)
IGNORED_KEYWORDS: frozenset[str] = frozenset(
    {
        "title",
        "default",
        "minimum",
        "maximum",
        "exclusiveMinimum",
        "minLength",
        "maxLength",
        "minItems",
        "maxItems",
        "pattern",
    }
)
ALLOWED_FORMATS: frozenset[str] = frozenset({"date-time", "date", "uuid"})
PARAMETER_KEYS: frozenset[str] = frozenset({"in", "name", "required", "schema", "description"})
REVIEWED_HEADER_PARAMS: frozenset[str] = frozenset({"Idempotency-Key"})

CANONICAL_PREFIX = "/api/v1/"
HTTP_METHODS = ("get", "post", "put", "patch", "delete")
OPERATION_KEYS = frozenset(
    {"operationId", "summary", "description", "tags", "deprecated"}
    | {"parameters", "requestBody", "responses"}
)
REQUEST_BODY_KEYS = frozenset({"content", "required"})
RESPONSE_KEYS = frozenset({"content", "description"})
JSON_MEDIA = "application/json"
REF_PREFIX = "#/components/schemas/"
RESPONSE_MAP = "ResponseSchemas"
REQUEST_MAP = "RequestSchemas"

_SCALARS = {"string": "string", "integer": "number", "number": "number", "boolean": "boolean"}
_SCALARS["null"] = "null"
_STRUCTURAL = ("properties", "additionalProperties", "propertyNames", "items", "required")
_IDENTIFIER = re.compile(r"^[A-Za-z_$][A-Za-z0-9_$]*$")

# The literal gates frontend/src is scanned by. The band-edge and plus-copy
# patterns are pinned to tests/unit/test_score_threshold_guard.py (and the
# numbers to backend/services/scoring.py) by a parity test.
BAND_EDGE_PATTERN = r"(?:>=|≥)\s*(85|65)\b"
PLUS_COPY_PATTERN = r"\b75\+"
_EMAIL = re.compile(r"[A-Za-z0-9._%+-]+@[A-Za-z0-9-]+(?:\.[A-Za-z0-9-]+)+")
SCREEN_PATTERNS: tuple[tuple[str, re.Pattern[str]], ...] = (
    ("masked borrower id", re.compile(r"B-[0-9A-Z]{13}")),
    ("phone number", re.compile(r"(?:\+?1[-.\s]?)?\(?\d{3}\)?[-.\s]?\d{3}[-.\s]?\d{4}\b")),
    ("url", re.compile(r"https?://")),
    ("score band edge", re.compile(BAND_EDGE_PATTERN)),
    ("threshold copy", re.compile(PLUS_COPY_PATTERN)),
    ("mock import path", re.compile(r"/mocks/")),
    ("mock service worker", re.compile(r"mockServiceWorker")),
)

HEADER_COMMENT = (
    "// ResponseSchemas is the PRESENCE view of every 2xx body: FastAPI serializes every",
    "// declared field, so each property is present and nullability comes only from the",
    "// schema. Schemas reached from routes serialized with exclude_unset (ABSENT_KEY_ROOTS",
    "// in the generator) keep their declared required list. RequestSchemas is the DECLARED",
    "// view of request bodies and parameters. ApiOperations maps each canonical /api/v1",
    "// operation to its parameters, body and 2xx union. Import with `import type` only.",
)


class UnsupportedSchema(ValueError):
    """A construct the emitter does not model; ``pointer`` locates it."""

    def __init__(self, pointer: str, keyword: str, detail: str = "") -> None:
        self.pointer = pointer
        self.keyword = keyword
        message = f"{pointer}: unsupported {keyword}"
        super().__init__(f"{message} ({detail})" if detail else message)


def screen_text(text: str, pointer: str) -> None:
    """Fail closed on PII/egress shapes and on the frontend literal gates."""

    for match in _EMAIL.finditer(text):
        if not match.group(0).endswith(".example"):
            raise UnsupportedSchema(pointer, "content-screen", "email address")
    for name, pattern in SCREEN_PATTERNS:
        if pattern.search(text):
            raise UnsupportedSchema(pointer, "content-screen", name)


def _token(value: str) -> str:
    return value.replace("~", "~0").replace("/", "~1")


def _schema_pointer(name: str) -> str:
    return f"#/components/schemas/{_token(name)}"


def _op_pointer(path: str, method: str) -> str:
    return f"#/paths/{_token(path)}/{method}"


def _ref_name(ref: Any, pointer: str, schemas: dict[str, Any]) -> str:
    if not isinstance(ref, str) or not ref.startswith(REF_PREFIX):
        raise UnsupportedSchema(f"{pointer}/$ref", "$ref", f"only {REF_PREFIX}X is modelled")
    name = ref[len(REF_PREFIX) :].replace("~1", "/").replace("~0", "~")
    if name not in schemas:
        raise UnsupportedSchema(f"{pointer}/$ref", "$ref", f"unknown schema {name!r}")
    return name


def _child_schemas(schema: dict[str, Any], pointer: str) -> Iterator[tuple[Any, str]]:
    """Yield the sub-schemas of a schema object (never the keys of a properties map)."""

    for key in ("items", "additionalProperties", "propertyNames"):
        value = schema.get(key)
        if isinstance(value, dict):
            yield value, f"{pointer}/{key}"
    for index, member in enumerate(schema.get("anyOf") or []):
        yield member, f"{pointer}/anyOf/{index}"
    properties = schema.get("properties")
    if isinstance(properties, dict):
        for name, value in properties.items():
            yield value, f"{pointer}/properties/{_token(name)}"


def _direct_refs(schema: Any, pointer: str, schemas: dict[str, Any]) -> Iterator[str]:
    if not isinstance(schema, dict):
        return
    if "$ref" in schema:
        yield _ref_name(schema["$ref"], pointer, schemas)
    for child, child_pointer in _child_schemas(schema, pointer):
        yield from _direct_refs(child, child_pointer, schemas)


def _closure(roots: Iterable[tuple[Any, str]], schemas: dict[str, Any]) -> set[str]:
    seen: set[str] = set()
    pending = [name for schema, pointer in roots for name in _direct_refs(schema, pointer, schemas)]
    while pending:
        name = pending.pop()
        if name in seen:
            continue
        seen.add(name)
        pending.extend(_direct_refs(schemas[name], _schema_pointer(name), schemas))
    return seen


def _schemas(spec: dict[str, Any]) -> dict[str, Any]:
    components = spec.get("components") or {}
    schemas = components.get("schemas") or {}
    if not isinstance(schemas, dict):
        raise UnsupportedSchema("#/components/schemas", "components", "not an object")
    return schemas


def _operations(spec: dict[str, Any]) -> Iterator[tuple[str, str, dict[str, Any]]]:
    paths = spec.get("paths") or {}
    for path in sorted(paths):
        if not path.startswith(CANONICAL_PREFIX):
            continue
        for method in HTTP_METHODS:
            operation = paths[path].get(method)
            if operation is not None:
                yield path, method, operation


def _success_schemas(path: str, method: str, operation: dict[str, Any]) -> list[tuple[Any, str]]:
    pointer = _op_pointer(path, method)
    responses = operation.get("responses") or {}
    found: list[tuple[Any, str]] = []
    for status in sorted(code for code in responses if str(code).startswith("2")):
        response = responses[status]
        where = f"{pointer}/responses/{status}"
        extra = set(response) - RESPONSE_KEYS
        if extra:
            raise UnsupportedSchema(where, sorted(extra)[0], "2xx response key")
        content = response.get("content")
        if not isinstance(content, dict) or set(content) != {JSON_MEDIA}:
            raise UnsupportedSchema(where, "content", "a 2xx body must be exactly application/json")
        media = content[JSON_MEDIA]
        if set(media) != {"schema"}:
            raise UnsupportedSchema(f"{where}/content", "media", "only a schema is modelled")
        found.append((media["schema"], f"{where}/content/{_token(JSON_MEDIA)}/schema"))
    if not found:
        raise UnsupportedSchema(pointer, "responses", "no 2xx response")
    return found


def _request_roots(path: str, method: str, operation: dict[str, Any]) -> list[tuple[Any, str]]:
    pointer = _op_pointer(path, method)
    roots: list[tuple[Any, str]] = []
    for index, parameter in enumerate(operation.get("parameters") or []):
        if isinstance(parameter, dict) and "schema" in parameter:
            roots.append((parameter["schema"], f"{pointer}/parameters/{index}/schema"))
    body = operation.get("requestBody")
    if isinstance(body, dict):
        media = (body.get("content") or {}).get(JSON_MEDIA)
        if isinstance(media, dict) and "schema" in media:
            roots.append((media["schema"], f"{pointer}/requestBody/content/schema"))
    return roots


def response_closure(spec: dict[str, Any]) -> set[str]:
    """Names reachable by $ref from every canonical 2xx JSON schema."""

    schemas = _schemas(spec)
    roots = [root for p, m, op in _operations(spec) for root in _success_schemas(p, m, op)]
    return _closure(roots, schemas)


def request_closure(spec: dict[str, Any]) -> set[str]:
    """Names reachable by $ref from canonical request bodies and parameters."""

    schemas = _schemas(spec)
    roots = [root for p, m, op in _operations(spec) for root in _request_roots(p, m, op)]
    return _closure(roots, schemas)


def _absent_closure(spec: dict[str, Any]) -> set[str]:
    """ABSENT_KEY_ROOTS present in the spec plus everything they reach by $ref."""

    schemas = _schemas(spec)
    roots = {name for name in ABSENT_KEY_ROOTS if name in schemas}
    return roots | _closure(((schemas[name], _schema_pointer(name)) for name in roots), schemas)


def _check_shared_schemas(spec: dict[str, Any], absent: set[str]) -> None:
    """An absent-view schema also served in full elsewhere must be all-required."""

    schemas = _schemas(spec)
    other_roots: list[tuple[Any, str]] = []
    for path, method, operation in _operations(spec):
        for schema, pointer in _success_schemas(path, method, operation):
            ref = schema.get("$ref") if isinstance(schema, dict) else None
            if isinstance(ref, str) and ref[len(REF_PREFIX) :] in ABSENT_KEY_ROOTS:
                continue
            other_roots.append((schema, pointer))
    for name in sorted(absent & _closure(other_roots, schemas)):
        schema = schemas[name]
        declared = set((schema.get("properties") or {}).keys())
        missing = sorted(declared - set(schema.get("required") or []))
        if missing:
            raise UnsupportedSchema(
                _schema_pointer(name),
                "required",
                f"{name} is served with exclude_unset and in full elsewhere; "
                f"{', '.join(missing)} must be required or the model split",
            )


class _View:
    def __init__(self, schemas: dict[str, Any], map_name: str, presence: bool) -> None:
        self.schemas = schemas
        self.map_name = map_name
        self.presence = presence

    def with_presence(self, presence: bool) -> _View:
        return _View(self.schemas, self.map_name, presence)


def _check_keywords(schema: Any, pointer: str) -> dict[str, Any]:
    if not isinstance(schema, dict):
        raise UnsupportedSchema(pointer, "schema", "not a schema object")
    for key in schema:
        if key not in ALLOWED_KEYWORDS:
            raise UnsupportedSchema(f"{pointer}/{_token(key)}", key)
    if "format" in schema and schema["format"] not in ALLOWED_FORMATS:
        raise UnsupportedSchema(f"{pointer}/format", "format", str(schema["format"]))
    if "type" in schema and not isinstance(schema["type"], str):
        raise UnsupportedSchema(f"{pointer}/type", "type", "a type list is not modelled")
    if "description" in schema:
        description = schema["description"]
        if not isinstance(description, str):
            raise UnsupportedSchema(f"{pointer}/description", "description", "not a string")
        screen_text(description, f"{pointer}/description")
    return schema


def _literal(value: Any, pointer: str) -> str:
    if isinstance(value, str):
        screen_text(value, pointer)
    elif value is not None and not isinstance(value, bool | int | float):
        raise UnsupportedSchema(pointer, "literal", "only JSON scalars are modelled")
    return json.dumps(value)


def _top_level_union(text: str) -> bool:
    depth = 0
    quoted = False
    escaped = False
    for char in text:
        if quoted:
            if escaped:
                escaped = False
            elif char == "\\":
                escaped = True
            elif char == '"':
                quoted = False
        elif char == '"':
            quoted = True
        elif char in "([{<":
            depth += 1
        elif char in ")]}>":
            depth -= 1
        elif char == "|" and depth == 0:
            return True
    return False


def _map_ref(map_name: str, name: str) -> str:
    key = f"'{name}'" if "'" not in name and "\\" not in name else json.dumps(name)
    return f"{map_name}[{key}]"


def _key(name: str) -> str:
    return name if _IDENTIFIER.match(name) else json.dumps(name)


def _jsdoc(description: str | None, indent: str) -> list[str]:
    if not description:
        return []
    text = description.replace("*/", "*\\/").replace("\u2028", "\\u2028").replace("\u2029", "\\u2029")
    lines = [line.rstrip() for line in text.strip().splitlines()]
    if len(lines) == 1:
        return [f"{indent}/** {lines[0]} */"]
    body = [f"{indent} * {line}" if line else f"{indent} *" for line in lines]
    return [f"{indent}/**", *body, f"{indent} */"]


def _type(schema: Any, pointer: str, view: _View, depth: int) -> str:
    schema = _check_keywords(schema, pointer)
    if "$ref" in schema:
        if any(key in schema for key in ("anyOf", "enum", "const", "type", *_STRUCTURAL)):
            raise UnsupportedSchema(pointer, "$ref", "a $ref with structural siblings")
        return _map_ref(view.map_name, _ref_name(schema["$ref"], pointer, view.schemas))
    if "anyOf" in schema:
        members = schema["anyOf"]
        if not isinstance(members, list) or not members:
            raise UnsupportedSchema(f"{pointer}/anyOf", "anyOf", "must be a non-empty list")
        if any(key in schema for key in ("enum", "const", "type", *_STRUCTURAL)):
            raise UnsupportedSchema(pointer, "anyOf", "anyOf with structural siblings")
        rendered = [
            _type(member, f"{pointer}/anyOf/{index}", view, depth)
            for index, member in enumerate(members)
        ]
        # `datetime | str` serializes as two string members: keep the first of each.
        return " | ".join(dict.fromkeys(rendered))
    if "enum" in schema:
        values = schema["enum"]
        if not isinstance(values, list) or not values:
            raise UnsupportedSchema(f"{pointer}/enum", "enum", "must be a non-empty list")
        return " | ".join(
            _literal(value, f"{pointer}/enum/{index}") for index, value in enumerate(values)
        )
    if "const" in schema:
        return _literal(schema["const"], f"{pointer}/const")
    kind = schema.get("type")
    if kind is None and any(key in schema for key in _STRUCTURAL):
        kind = "array" if "items" in schema else "object"
    if kind is None:
        return "unknown"
    if kind in _SCALARS:
        present = [key for key in _STRUCTURAL if key in schema]
        if present:
            raise UnsupportedSchema(f"{pointer}/{present[0]}", present[0], f"on type {kind}")
        return _SCALARS[kind]
    if kind == "array":
        if "items" not in schema:
            raise UnsupportedSchema(pointer, "items", "an array without items")
        inner = _type(schema["items"], f"{pointer}/items", view, depth)
        return f"({inner})[]" if _top_level_union(inner) else f"{inner}[]"
    if kind == "object":
        return _object(schema, pointer, view, depth)
    raise UnsupportedSchema(f"{pointer}/type", "type", str(kind))


def _object(schema: dict[str, Any], pointer: str, view: _View, depth: int) -> str:
    properties = schema.get("properties")
    extra = schema.get("additionalProperties")
    names = schema.get("propertyNames")
    if properties is None:
        if "required" in schema:
            raise UnsupportedSchema(f"{pointer}/required", "required", "without properties")
        if isinstance(extra, dict):
            value = _type(extra, f"{pointer}/additionalProperties", view, depth)
            if names is None:
                return f"{{ [key: string]: {value} }}"
            return f"{{ [K in {_property_names(names, pointer)}]?: {value} }}"
        if names is not None:
            raise UnsupportedSchema(f"{pointer}/propertyNames", "propertyNames", "without a value schema")
        if extra is None or extra is True:
            return "{ [key: string]: unknown }"
        raise UnsupportedSchema(f"{pointer}/additionalProperties", "additionalProperties", "false without properties")
    if not isinstance(properties, dict):
        raise UnsupportedSchema(f"{pointer}/properties", "properties", "not an object")
    if isinstance(extra, dict) or extra is True:
        raise UnsupportedSchema(
            f"{pointer}/additionalProperties", "additionalProperties", "alongside properties"
        )
    if names is not None:
        raise UnsupportedSchema(f"{pointer}/propertyNames", "propertyNames", "alongside properties")
    if not properties:
        return "Record<string, never>"
    required = schema.get("required") or []
    if not isinstance(required, list) or not set(required) <= set(properties):
        raise UnsupportedSchema(f"{pointer}/required", "required", "names an undeclared property")
    indent = "  " * (depth + 1)
    lines = ["{"]
    for name in sorted(properties):
        prop_pointer = f"{pointer}/properties/{_token(name)}"
        prop_schema = _check_keywords(properties[name], prop_pointer)
        lines.extend(_jsdoc(prop_schema.get("description"), indent))
        optional = "" if view.presence or name in required else "?"
        lines.append(f"{indent}{_key(name)}{optional}: {_type(prop_schema, prop_pointer, view, depth + 1)};")
    lines.append("  " * depth + "}")
    return "\n".join(lines)


def _property_names(names: Any, pointer: str) -> str:
    where = f"{pointer}/propertyNames"
    names = _check_keywords(names, where)
    if "enum" not in names or names.get("type", "string") != "string" or set(names) - {"enum", "type"}:
        raise UnsupportedSchema(where, "propertyNames", "only a string enum is modelled")
    return _type(names, where, _View({}, REQUEST_MAP, False), 0)


def _schema_map(
    spec: dict[str, Any], names: set[str], map_name: str, presence_for: set[str]
) -> list[str]:
    schemas = _schemas(spec)
    lines = [f"export interface {map_name} {{"]
    for name in sorted(names):
        pointer = _schema_pointer(name)
        schema = _check_keywords(schemas[name], pointer)
        view = _View(schemas, map_name, name in presence_for)
        lines.extend(_jsdoc(schema.get("description"), "  "))
        lines.append(f"  {_key(name)}: {_type(schema, pointer, view, 1)};")
    lines.append("}")
    return lines


def _parameter_groups(
    path: str, method: str, operation: dict[str, Any], view: _View
) -> dict[str, str]:
    op_key = f"{method.upper()} {path}"
    groups: dict[str, list[str]] = {"path": [], "query": [], "header": []}
    for index, parameter in enumerate(operation.get("parameters") or []):
        where = f"{_op_pointer(path, method)}/parameters/{index}"
        if not isinstance(parameter, dict):
            raise UnsupportedSchema(where, "parameter", op_key)
        extra = set(parameter) - PARAMETER_KEYS
        if extra:
            raise UnsupportedSchema(where, sorted(extra)[0], f"parameter key on {op_key}")
        location = parameter.get("in")
        name = parameter.get("name")
        if location not in groups or not isinstance(name, str) or "schema" not in parameter:
            raise UnsupportedSchema(where, "in", f"{op_key} parameter {name!r} in {location!r}")
        if location == "header" and name not in REVIEWED_HEADER_PARAMS:
            raise UnsupportedSchema(
                where, "header", f"{op_key} header {name!r} is not in REVIEWED_HEADER_PARAMS"
            )
        description = parameter.get("description")
        if description is not None:
            if not isinstance(description, str):
                raise UnsupportedSchema(f"{where}/description", "description", "not a string")
            screen_text(description, f"{where}/description")
        member = groups[location]
        member.extend(_jsdoc(description, "      "))
        optional = "" if parameter.get("required") is True else "?"
        rendered = _type(parameter["schema"], f"{where}/schema", view, 3)
        member.append(f"      {_key(name)}{optional}: {rendered};")
    return {
        location: "{\n" + "\n".join(lines) + "\n    }" if lines else "Record<string, never>"
        for location, lines in groups.items()
    }


def _body(path: str, method: str, operation: dict[str, Any], view: _View) -> str:
    body = operation.get("requestBody")
    if body is None:
        return "body: never"
    where = f"{_op_pointer(path, method)}/requestBody"
    if not isinstance(body, dict) or set(body) - REQUEST_BODY_KEYS:
        raise UnsupportedSchema(where, "requestBody", "keys must be content and required")
    content = body.get("content")
    if not isinstance(content, dict) or set(content) != {JSON_MEDIA}:
        raise UnsupportedSchema(f"{where}/content", "content", "the body must be exactly application/json")
    media = content[JSON_MEDIA]
    if not isinstance(media, dict) or set(media) != {"schema"}:
        raise UnsupportedSchema(f"{where}/content", "media", "only a schema is modelled")
    rendered = _type(media["schema"], f"{where}/content/{_token(JSON_MEDIA)}/schema", view, 2)
    return f"body{'' if body.get('required') is True else '?'}: {rendered}"


def _operation_map(spec: dict[str, Any]) -> list[str]:
    schemas = _schemas(spec)
    request = _View(schemas, REQUEST_MAP, False)
    response = _View(schemas, RESPONSE_MAP, True)
    members: list[tuple[str, list[str]]] = []
    for path, method, operation in _operations(spec):
        pointer = _op_pointer(path, method)
        extra = set(operation) - OPERATION_KEYS
        if extra:
            raise UnsupportedSchema(pointer, sorted(extra)[0], "operation key")
        groups = _parameter_groups(path, method, operation, request)
        ok = " | ".join(
            _type(schema, where, response, 2)
            for schema, where in _success_schemas(path, method, operation)
        )
        members.append(
            (
                f"{method.upper()} {path}",
                [
                    f"    pathParams: {groups['path']};",
                    f"    query: {groups['query']};",
                    f"    headers: {groups['header']};",
                    f"    {_body(path, method, operation, request)};",
                    f"    ok: {ok};",
                ],
            )
        )
    lines = ["export interface ApiOperations {"]
    for key, body in sorted(members):
        lines.append(f"  {json.dumps(key)}: {{")
        lines.extend(body)
        lines.append("  };")
    lines.append("}")
    return lines


def render(spec: dict[str, Any]) -> str:
    """Return the api.gen.ts text for an OpenAPI document (raises UnsupportedSchema)."""

    absent = _absent_closure(spec)
    _check_shared_schemas(spec, absent)
    responses = response_closure(spec)
    requests = request_closure(spec)
    parts = [
        [BANNER, *HEADER_COMMENT],
        _schema_map(spec, responses, RESPONSE_MAP, responses - absent),
        _schema_map(spec, requests, REQUEST_MAP, set()),
        [
            "export type ApiResponse<K extends keyof ResponseSchemas> = ResponseSchemas[K];",
            "export type ApiRequest<K extends keyof RequestSchemas> = RequestSchemas[K];",
        ],
        _operation_map(spec),
        [
            "export type ApiOk<K extends keyof ApiOperations> = ApiOperations[K]['ok'];",
            "export type ApiBody<K extends keyof ApiOperations> = ApiOperations[K]['body'];",
        ],
    ]
    return "\n\n".join("\n".join(part) for part in parts) + "\n"


def write_output(text: str) -> str:
    """Write the module on every call; return 'updated' or 'unchanged'."""

    previous = OUTPUT.read_text(encoding="utf-8") if OUTPUT.is_file() else None
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(text, encoding="utf-8", newline="\n")
    return "unchanged" if previous == text else "updated"


def _check(text: str) -> int:
    if not OUTPUT.is_file():
        print(f"missing: {OUTPUT_REL}: run python tools/regen_openapi_baseline.py")
        return 1
    committed = OUTPUT.read_text(encoding="utf-8")
    if committed == text:
        print(f"current: {OUTPUT_REL}")
        return 0
    diff = difflib.unified_diff(
        committed.splitlines(keepends=True),
        text.splitlines(keepends=True),
        fromfile=f"{OUTPUT_REL} (committed)",
        tofile=f"{OUTPUT_REL} (rendered)",
    )
    print(f"stale: {OUTPUT_REL}: run python tools/regen_openapi_baseline.py")
    sys.stdout.writelines(list(diff)[:40])
    return 1


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true", help=f"rewrite {OUTPUT_REL}")
    mode.add_argument("--check", action="store_true", help="exit 1 when the module is stale")
    args = parser.parse_args(argv)
    spec = json.loads(BASELINE.read_text(encoding="utf-8"))
    try:
        text = render(spec)
    except UnsupportedSchema as exc:
        print(f"unsupported schema at {exc.pointer} ({exc.keyword}): {exc}", file=sys.stderr)
        return 2
    if args.check:
        return _check(text)
    print(f"{write_output(text)}: {OUTPUT_REL}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
