"""Deterministic proof margins (wow-ai-1 phase 1) pinned by golden fixtures.

``tests/fixtures/borrower_proof_margins_golden.json`` is GENERATED by running
the builder over the case rows below, never by hand arithmetic:

    PYTHONPATH=. python tests/unit/test_borrower_proof_margins.py --regen

A diff in the regenerated file is a behaviour change to review, not noise.
The cases pin: clears and short; half-bps boundaries at even and odd
``min_spread`` through ``rate_spread_bps_at_par_shift`` (the fixture par
0.04875 puts eighth-point coupons on exact .5 bps, so half-even and half-up
disagree at the odd minimum); the SQL rate gate (current_rate 0, 1.0, 15.0);
a spread that the note rate does not reproduce; a missing par; a listing that
holds; and an offer the recomputation does not reproduce.
"""

from __future__ import annotations

import inspect
import json
import re
import sys
from pathlib import Path
from typing import Any

import pytest

from backend.schemas.proof import ProofMargin
from backend.services.proof_policy import borrower_proof_assets
from backend.services.repositories import databricks_borrower_proof as proof_module
from backend.services.repositories import databricks_borrower_proof_margins as margins_module
from backend.services.repositories.databricks_borrower_proof_margins import (
    OfferInputs,
    _offer_inputs,
    build_proof_margins,
)
from backend.services.repositories.databricks_borrowers import _build_borrower_proof
from backend.services.scoring import (
    RATE_SCENARIO_MAX_SHIFT_BPS,
    in_the_money,
    next_best_offer,
    rate_spread_bps,
    rate_spread_bps_at_par_shift,
)
from tests.fixtures import mock_population as mock_data

GOLDEN_PATH = Path(__file__).resolve().parents[1] / "fixtures" / "borrower_proof_margins_golden.json"

_BASE_ROW: dict[str, Any] = {
    "current_rate": 5.75,
    "market_rate_fraction": 0.04875,
    "rate_spread_bps": 88,
    "equity_pct": 46,
    "has_permit": False,
    "has_heloc_propensity_trigger": False,
    "listed_for_sale": False,
    "is_investor": False,
    "is_current_customer": False,
    "is_competitor_lien": False,
    "min_spread_bps_applied": 75,
    "min_equity_pct_applied": 15,
    "heloc_equity_min_applied": 35,
    "cashout_equity_min_applied": 25,
    "retention_min_spread_applied": 50,
    "recommended_offer_code": "refi_plus_heloc",
}

# id -> (overrides on _BASE_ROW, what the case pins)
_CASES: dict[str, tuple[dict[str, Any], str]] = {
    "clears_refi_plus_heloc": ({}, "Clears the screen; the par flip lands at +13 (87.5 -> 74.5 bps rounds to 74)."),
    "short_heloc": (
        {"current_rate": 5.25, "rate_spread_bps": 37, "has_permit": True, "equity_pct": 48, "recommended_offer_code": "heloc"},
        "Below the screen: the break-even is a par fall.",
    ),
    "half_bps_odd_min_spread": (
        {"min_spread_bps_applied": 71},
        "Odd minimum at an exact .5 bps boundary: half-even flips at +17, half-up would say +18.",
    ),
    "half_bps_even_min_spread": (
        {"min_spread_bps_applied": 72},
        "Even minimum at the same boundaries: half-even and half-up agree.",
    ),
    "half_bps_short_odd_min_spread": (
        {"current_rate": 5.5, "rate_spread_bps": 62, "equity_pct": 30, "min_spread_bps_applied": 71, "recommended_offer_code": "cash_out"},
        "Short of an odd minimum: half-even clears at -9, half-up would say -8.",
    ),
    "eighth_coupon_live_par": (
        {"current_rate": 0.06375 * 100, "market_rate_fraction": 0.0626, "rate_spread_bps": 11, "min_spread_bps_applied": 11,
         "equity_pct": 20, "recommended_offer_code": "refi"},
        "An eighth-point coupon against a two-decimal FRED par; current_rate carries its DOUBLE tail.",
    ),
    "holds_wide_spread": (
        {"current_rate": 6.75, "rate_spread_bps": 188, "equity_pct": 39},
        "No flip inside the +/-100 bps grid: both par margins hold.",
    ),
    "purchase_listing_holds": (
        {"current_rate": 6.5, "rate_spread_bps": 162, "equity_pct": 56, "listed_for_sale": True, "is_current_customer": True,
         "recommended_offer_code": "purchase"},
        "The listing selects the offer: the searches find no flip and say why.",
    ),
    "gated_paid_off_lien": (
        {"current_rate": 0.0, "rate_spread_bps": 0, "equity_pct": 100, "recommended_offer_code": "cash_out"},
        "No active lien: current_rate 0 fails the rate gate; par margins are unavailable.",
    ),
    "gated_at_rate_floor": (
        {"current_rate": 1.0, "rate_spread_bps": 0, "equity_pct": 40, "recommended_offer_code": "cash_out"},
        "A rate clamped at the 1% bound is not in range.",
    ),
    "gated_at_rate_cap": (
        {"current_rate": 15.0, "rate_spread_bps": 0, "equity_pct": 40, "recommended_offer_code": "cash_out"},
        "A rate clamped at the 15% bound is not in range.",
    ),
    "spread_drift": (
        {"rate_spread_bps": 90},
        "The note rate reproduces 88 bps, the row says 90: par margins fail closed.",
    ),
    "no_par_rate": ({"market_rate_fraction": 0.0}, "No par on the row."),
    "offer_drift": (
        {"recommended_offer_code": "refi"},
        "The recomputed offer (refi_plus_heloc) differs from the dossier's: both flips are unavailable.",
    ),
    "equity_short_investor": (
        {"current_rate": 5.375, "rate_spread_bps": 50, "equity_pct": 10, "is_investor": True, "recommended_offer_code": "investor"},
        "Equity under the refi equity threshold.",
    ),
    "spread_clears_equity_short": (
        {"current_rate": 6.625, "market_rate_fraction": 0.05745, "rate_spread_bps": 88, "equity_pct": 10,
         "recommended_offer_code": "nurture"},
        "Spread over its minimum, equity under its own: in_the_money is False, so the row does not clear the "
        "refi screen and no par move inside the grid makes it (the dossier chip reads 'Below refi screen').",
    ),
}

_FORBIDDEN_COPY = re.compile(r"deny|declin|adverse|reason|eligib|credit[- ]?score|today", re.IGNORECASE)


def _case_row(case_id: str) -> dict[str, Any]:
    overrides, _ = _CASES[case_id]
    return {**_BASE_ROW, **overrides}


def _build(row: dict[str, Any]) -> list[ProofMargin]:
    return build_proof_margins(row, dossier_offer=str(row["recommended_offer_code"]))


def _generate() -> dict[str, Any]:
    cases = []
    for case_id, (_, note) in _CASES.items():
        row = _case_row(case_id)
        cases.append({
            "id": case_id,
            "note": note,
            "row": row,
            "margins": [margin.model_dump() for margin in _build(row)],
        })
    return {
        "_generated_by": "PYTHONPATH=. python tests/unit/test_borrower_proof_margins.py --regen",
        "cases": cases,
    }


GOLDEN = json.loads(GOLDEN_PATH.read_text()) if GOLDEN_PATH.exists() else {"cases": []}


def test_golden_file_covers_every_case() -> None:
    assert [case["id"] for case in GOLDEN["cases"]] == list(_CASES)


@pytest.mark.parametrize("case", GOLDEN["cases"], ids=[case["id"] for case in GOLDEN["cases"]])
def test_margins_match_golden(case: dict[str, Any]) -> None:
    assert case["row"] == _case_row(case["id"]), "the golden row drifted from the case table; regenerate"
    assert [margin.model_dump() for margin in _build(case["row"])] == case["margins"], case["note"]


def _golden_margins(case_id: str) -> dict[str, dict[str, Any]]:
    case = next(case for case in GOLDEN["cases"] if case["id"] == case_id)
    return {margin["key"]: margin for margin in case["margins"]}


def test_golden_pins_the_behaviours_the_cases_name() -> None:
    clears = _golden_margins("clears_refi_plus_heloc")
    assert [clears[key]["direction"] for key in clears] == ["clears", "flips", "clears", "flips", "flips"]
    assert clears["par_break_even"]["value_text"] == (
        "Drops below the refi screen if 30-year par rises 13 bps to 5.01%"
    )
    assert _golden_margins("short_heloc")["spread_screen"]["direction"] == "short"
    odd = _golden_margins("half_bps_odd_min_spread")["par_break_even"]["value_text"]
    assert "rises 17 bps" in odd
    assert "falls 9 bps" in _golden_margins("half_bps_short_odd_min_spread")["par_break_even"]["value_text"]
    for case_id in ("gated_paid_off_lien", "gated_at_rate_floor", "gated_at_rate_cap", "spread_drift", "no_par_rate"):
        margins = _golden_margins(case_id)
        assert margins["par_break_even"]["direction"] == "unavailable", case_id
        assert margins["offer_flip_par"]["direction"] == "unavailable", case_id
        assert margins["spread_screen"]["direction"] in {"clears", "short"}, case_id
    purchase = _golden_margins("purchase_listing_holds")
    assert purchase["offer_flip_equity"]["direction"] == "holds"
    assert purchase["offer_flip_par"]["direction"] == "holds"
    assert purchase["offer_flip_par"]["value_text"].startswith("The listing signal selects this offer")
    drift = _golden_margins("offer_drift")
    assert drift["offer_flip_equity"]["direction"] == "unavailable"
    assert drift["offer_flip_par"]["direction"] == "unavailable"
    wide = _golden_margins("holds_wide_spread")
    assert wide["par_break_even"]["direction"] == "holds"
    assert _golden_margins("equity_short_investor")["equity_floor"]["direction"] == "short"
    equity_short = _golden_margins("spread_clears_equity_short")
    assert equity_short["spread_screen"]["direction"] == "short"
    assert equity_short["spread_screen"]["value_text"] == (
        "Spread clears the refi screen's spread minimum by 13 bps; equity is 5 pts under its 15% minimum"
    )
    assert equity_short["par_break_even"]["direction"] == "holds"
    assert equity_short["par_break_even"]["value_text"] == (
        "No par move within ±100 bps clears the refi screen; equity is under its minimum"
    )


def test_offer_inputs_are_next_best_offer_arguments() -> None:
    assert list(OfferInputs._fields) == list(inspect.signature(next_best_offer).parameters)


def _mock_proof_row(borrower_id: str, **overrides: Any) -> dict[str, Any]:
    borrower = next(b for b in mock_data.BORROWERS if b.borrower_id == borrower_id)
    inputs = mock_data.BORROWER_OFFER_INPUTS[borrower_id]
    return {
        **borrower.model_dump(),
        **inputs,
        **mock_data.BORROWER_SCORE_COMPONENTS[borrower_id],
        "score_opportunity_score": borrower.opportunity_score,
        "score_signal_strength": borrower.confidence,
        "min_spread_bps_applied": inputs["min_spread_bps"],
        "min_equity_pct_applied": inputs["min_equity_pct"],
        "heloc_equity_min_applied": inputs["heloc_equity_min_pct"],
        "cashout_equity_min_applied": inputs["cashout_equity_min_pct"],
        "retention_min_spread_applied": inputs["retention_min_spread_bps"],
        "market_rate_fraction": borrower.why_panel.market_rate,
        "dossier_refreshed_at": "2026-04-20T06:12:00Z",
        "score_refreshed_at": "2026-04-20T06:12:00Z",
        **overrides,
    }


_PAR_MOVE = re.compile(r"\bpar (rises|falls) (\d+) bps? to ")


def _sweep_row(current_rate: float, equity_pct: int, min_spread_bps: int) -> dict[str, Any]:
    """A gate-passing row whose materialized spread is the note rate's own."""

    note = round(current_rate / 100.0, 7)
    spread = rate_spread_bps(note, _BASE_ROW["market_rate_fraction"])
    row = {**_BASE_ROW, "current_rate": current_rate, "rate_spread_bps": spread, "equity_pct": equity_pct,
           "min_spread_bps_applied": min_spread_bps}
    row["recommended_offer_code"] = next_best_offer(**_offer_inputs(row)._asdict())
    return row


def _invariant_rows() -> list[tuple[str, dict[str, Any]]]:
    rows = [(f"golden:{case_id}", _case_row(case_id)) for case_id in _CASES]
    rows += [(f"mock:{b.borrower_id}", _mock_proof_row(b.borrower_id)) for b in mock_data.BORROWERS]
    rows += [
        (f"sweep:{rate}/{equity}/{min_spread}", _sweep_row(rate, equity, min_spread))
        for rate in (4.75, 5.25, 5.75, 6.25, 6.75)
        for equity in (0, 10, 14, 15, 16, 46)
        for min_spread in (71, 75)
    ]
    return rows


def _first_screen_flip(row: dict[str, Any], inputs: OfferInputs) -> int | None:
    """Independently: the first grid step at which in_the_money differs from shift 0."""

    note = round(float(row["current_rate"]) / 100.0, 7)
    market = float(row["market_rate_fraction"])

    def itm(shift: int) -> bool:
        spread = rate_spread_bps_at_par_shift(note, market, shift)
        return in_the_money(spread, inputs.equity_pct, inputs.min_spread_bps, inputs.min_equity_pct)

    for magnitude in range(1, RATE_SCENARIO_MAX_SHIFT_BPS + 1):
        for shift in (magnitude, -magnitude):
            if itm(shift) != itm(0):
                return shift
    return None


_INVARIANT_ROWS = _invariant_rows()


@pytest.mark.parametrize(("row_id", "row"), _INVARIANT_ROWS, ids=[row_id for row_id, _ in _INVARIANT_ROWS])
def test_refi_screen_margins_agree_with_in_the_money(row_id: str, row: dict[str, Any]) -> None:
    """The refi-screen margins say what the dossier chip and the Rate Lever say.

    The chip reads ``why_panel.in_the_money`` and the Rate Lever counts
    ``in_the_money(rate_spread_bps_at_par_shift(...), equity, ...)``; the
    margins must agree with that predicate on every row, including a spread
    that clears its minimum while equity does not.
    """

    inputs = _offer_inputs(row)
    passes = in_the_money(inputs.rate_spread_bps, inputs.equity_pct, inputs.min_spread_bps, inputs.min_equity_pct)
    margins = {margin.key: margin for margin in _build(row)}
    screen, break_even = margins["spread_screen"], margins["par_break_even"]

    assert (screen.direction == "clears") == passes, row_id
    if not passes:
        assert "Clears the refi screen" not in screen.value_text, row_id
        assert "Meets the refi screen" not in screen.value_text, row_id

    if isinstance(margins_module._par_gate(row, inputs), str):
        assert break_even.direction == "unavailable", row_id
        return
    expected = _first_screen_flip(row, inputs)
    if expected is None:
        assert break_even.direction == "holds", row_id
        assert "Clears the refi screen if" not in break_even.value_text, row_id
        assert "Drops below the refi screen if" not in break_even.value_text, row_id
        return
    assert break_even.direction == "flips", row_id
    move = _PAR_MOVE.search(break_even.value_text)
    assert move is not None, break_even.value_text
    shift = int(move.group(2)) * (1 if move.group(1) == "rises" else -1)
    assert shift == expected, row_id
    assert break_even.value_text.startswith("Drops below" if passes else "Clears"), row_id


def test_the_invariant_rows_reach_every_refi_screen_branch() -> None:
    """Non-vacuity: the sweep holds spread-clears/equity-short rows, flips both ways and holds."""

    seen: set[tuple[bool, bool, str]] = set()
    for _row_id, row in _INVARIANT_ROWS:
        inputs = _offer_inputs(row)
        spread_ok = inputs.rate_spread_bps >= inputs.min_spread_bps
        equity_ok = inputs.equity_pct >= inputs.min_equity_pct
        seen.add((spread_ok, equity_ok, {m.key: m for m in _build(row)}["par_break_even"].direction))
    assert {(True, False, "holds"), (True, True, "flips"), (False, True, "flips"), (True, True, "holds")} <= seen
    assert (True, False, "flips") not in seen and (False, False, "flips") not in seen


@pytest.mark.parametrize(
    "overrides",
    [{}, {"market_rate_fraction": 0.05}, {"current_rate": 0.0}, {"recommended_offer_code": "refi"}],
    ids=["clean", "par_drift", "gated", "offer_drift"],
)
def test_margins_never_change_trusted_or_known_data_gaps(
    overrides: dict[str, Any], monkeypatch: pytest.MonkeyPatch
) -> None:
    row = _mock_proof_row("B-48291", **overrides)
    with_margins = _build_borrower_proof(row)
    monkeypatch.setattr(proof_module, "build_proof_margins", lambda *_args, **_kwargs: [])
    without_margins = _build_borrower_proof(row)

    assert with_margins.margins, "the proof carries margins"
    assert with_margins.trusted == without_margins.trusted
    assert with_margins.known_data_gaps == without_margins.known_data_gaps
    margin_text = {m.value_text for m in with_margins.margins} | {m.threshold for m in with_margins.margins}
    assert not any(text in gap for gap in with_margins.known_data_gaps for text in margin_text)


def test_a_clean_row_stays_trusted_when_its_par_margins_fail_closed() -> None:
    proof = _build_borrower_proof(_mock_proof_row("B-48291", market_rate_fraction=0.05))
    assert proof.trusted is True
    assert proof.known_data_gaps == []
    by_key = {margin.key: margin for margin in proof.margins}
    assert by_key["par_break_even"].direction == "unavailable"


def test_only_equity_and_the_par_derived_spread_are_perturbed(monkeypatch: pytest.MonkeyPatch) -> None:
    calls: list[dict[str, Any]] = []

    def spy(**kwargs: Any) -> str:
        calls.append(kwargs)
        return next_best_offer(**kwargs)

    monkeypatch.setattr(margins_module, "next_best_offer", spy)
    economic = {"rate_spread_bps", "equity_pct"}
    for case_id in _CASES:
        row = _case_row(case_id)
        fixed = {key: value for key, value in _offer_inputs(row)._asdict().items() if key not in economic}
        calls.clear()
        _build(row)
        assert calls, case_id
        for call in calls:
            assert {key: value for key, value in call.items() if key not in economic} == fixed, case_id
        assert len({call["equity_pct"] for call in calls}) > 1 or case_id == "offer_drift"


def test_margin_copy_avoids_credit_decision_vocabulary() -> None:
    texts = [
        text
        for case in GOLDEN["cases"]
        for margin in case["margins"]
        for text in (margin["label"], margin["value_text"], margin["threshold"])
    ]
    for borrower in mock_data.BORROWERS:
        for margin in _build_borrower_proof(_mock_proof_row(borrower.borrower_id)).margins:
            texts.extend((margin.label, margin.value_text, margin.threshold))
    assert texts
    assert [text for text in texts if _FORBIDDEN_COPY.search(text)] == []


def test_margin_sources_are_governed_proof_assets() -> None:
    assets = set(borrower_proof_assets())
    sources = {margin["source"] for case in GOLDEN["cases"] for margin in case["margins"]}
    assert sources
    assert sources <= assets


def test_note_rate_reconstruction_is_exact_for_eighth_point_coupons() -> None:
    coupons = [eighths / 8 for eighths in range(9, 120)]
    assert coupons[0] == 1.125 and coupons[-1] == 14.875
    for coupon in coupons:
        first_pos_rate = coupon / 100
        current_rate = first_pos_rate * 100  # gold: CAST(first_pos_rate * 100 AS DOUBLE)
        assert round(current_rate / 100.0, 7) == first_pos_rate, coupon


if __name__ == "__main__":
    if "--regen" not in sys.argv:
        raise SystemExit("usage: PYTHONPATH=. python tests/unit/test_borrower_proof_margins.py --regen")
    GOLDEN_PATH.write_text(json.dumps(_generate(), indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"wrote {GOLDEN_PATH}")
