"""Production-source coverage for the file-size architecture gate."""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

from tools import check_file_sizes

REPO_ROOT = Path(__file__).resolve().parents[2]


def test_default_file_size_roots_include_production_jobs_and_scripts() -> None:
    assert "jobs" in check_file_sizes.DEFAULT_INCLUDE_DIRS
    assert "scripts" in check_file_sizes.DEFAULT_INCLUDE_DIRS
    assert ".sh" in check_file_sizes.DEFAULT_SUFFIXES


def test_all_production_jobs_pass_hard_file_size_limit(tmp_path: Path) -> None:
    result = subprocess.run(
        [
            sys.executable,
            str(REPO_ROOT / "tools" / "check_file_sizes.py"),
            "--warn",
            "500",
            "--fail",
            "900",
            "--allowlist",
            str(tmp_path / "empty-allowlist.json"),
            "jobs",
        ],
        cwd=REPO_ROOT,
        text=True,
        capture_output=True,
        check=False,
    )

    assert result.returncode == 0, result.stdout + result.stderr


def test_new_deploy_lifecycle_shell_libraries_pass_without_allowlist(tmp_path: Path) -> None:
    lifecycle_files = sorted((REPO_ROOT / "scripts" / "lib").glob("*.sh"))
    assert lifecycle_files

    result = subprocess.run(
        [
            sys.executable,
            str(REPO_ROOT / "tools" / "check_file_sizes.py"),
            "--warn",
            "500",
            "--fail",
            "900",
            "--allowlist",
            str(tmp_path / "empty-allowlist.json"),
            *(str(path.relative_to(REPO_ROOT)) for path in lifecycle_files),
        ],
        cwd=REPO_ROOT,
        text=True,
        capture_output=True,
        check=False,
    )

    assert result.returncode == 0, result.stdout + result.stderr


GENERATED_BANNER = (
    "// GENERATED by tools/gen_api_types.py from tests/fixtures/openapi_baseline.json. "
    "Do not edit: run `python tools/regen_openapi_baseline.py`.\n"
)


def test_generated_files_map_is_exactly_the_api_types_module() -> None:
    expected = {"frontend/src/types/api.gen.ts": "tools/gen_api_types.py"}
    assert expected == check_file_sizes.GENERATED_FILES


def test_generated_exemption_needs_the_mapped_path_and_a_first_line_banner(tmp_path: Path) -> None:
    mapped = "frontend/src/types/api.gen.ts"
    with_banner = tmp_path / "with_banner.ts"
    with_banner.write_text(GENERATED_BANNER + "export type A = string;\n", encoding="utf-8")
    without_banner = tmp_path / "without_banner.ts"
    without_banner.write_text("export type A = string;\n", encoding="utf-8")
    banner_on_line_two = tmp_path / "line_two.ts"
    banner_on_line_two.write_text("// hand-written\n" + GENERATED_BANNER, encoding="utf-8")

    assert check_file_sizes._generated_exempt(mapped, with_banner) is True
    assert check_file_sizes._generated_exempt(mapped, without_banner) is False
    assert check_file_sizes._generated_exempt("frontend/src/types/other.ts", with_banner) is False
    assert check_file_sizes._generated_exempt(mapped, banner_on_line_two) is False


def test_real_gate_reports_the_generated_module_without_failing(tmp_path: Path) -> None:
    result = subprocess.run(
        [
            sys.executable,
            str(REPO_ROOT / "tools" / "check_file_sizes.py"),
            "--warn",
            "500",
            "--fail",
            "900",
            "--allowlist",
            str(tmp_path / "empty-allowlist.json"),
            "frontend/src/types/api.gen.ts",
        ],
        cwd=REPO_ROOT,
        text=True,
        capture_output=True,
        check=False,
    )

    assert result.returncode == 0, result.stdout + result.stderr
    assert "GENERATED: frontend/src/types/api.gen.ts:" in result.stdout
